infectedzone, landzdown UID 코드 추가 및 충돌 해결
WHS-Killer-Whale/WhatsMyName_DarkWeb pull request #14
Opened 2023-12-26 01:45 UTC by jny4867

2023-12-27 03:48 UTC, hhtboy requested changes
불필요한 라이브러리가 추가된 것 같습니다

2023-12-27 03:48 UTC, hhtboy commented on main.py
> +from selenium import webdriver
불필요한 selenium 라이브러리 추가

2023-12-27 04:28 UTC, jny4867 commented on main.py
> +from selenium import webdriver
라이브러리 수정 완료 했습니다!

2023-12-28 07:35 UTC, hhtboy approved these changes

2023-12-28 07:35 UTC, merged