megatop, dark2web, bdfclub, infectedZone, Wjunction 추가
WHS-Killer-Whale/WhatsMyName_DarkWeb pull request #7
Opened 2023-12-13 09:25 UTC by yyyy7246

## 5개의 사이트가 메커니즘이 같음

1. url, header 값을 주고 requests로 접속
<img width="556" alt="image" src="https://github.com/WHS-Killer-Whale/WhatsMyName_DarkWeb/assets/55538662/b6f2fd99-58e4-4635-af13-8e39e33ec387"><br/><br/><br/>

2. 쿠키값 획득
<img width="492" alt="image" src="https://github.com/WHS-Killer-Whale/WhatsMyName_DarkWeb/assets/55538662/a60562e5-befe-4d1e-a2ad-2a613e7c79e9"><br/><br/><br/>

3. html에 있는 data-csrf값 획득
<img width="830" alt="image" src="https://github.com/WHS-Killer-Whale/WhatsMyName_DarkWeb/assets/55538662/a18965b7-2209-41f9-a059-d830e2263ef6"><br/><br/><br/>

4. 위 값들을 이용해 인증을 거치고 api를 통하여 json 검색
<img width="827" alt="image" src="https://github.com/WHS-Killer-Whale/WhatsMyName_DarkWeb/assets/55538662/fe5f556d-1eca-47b4-844c-655e44a0d6a0"><br/><br/><br/>

5. json의 값들을 파싱하여 소문자로 변환후 완전히 일치하는지 값을 비교 
<img width="294" alt="image" src="https://github.com/WHS-Killer-Whale/WhatsMyName_DarkWeb/assets/55538662/8bc2ad6b-b55f-4ee8-95c9-0c31d67b4108"><br/><br/><br/>

6. 공백, 대소문자 구분 등 오류 없음을 확인

2023-12-14 04:09 UTC, hhtboy requested changes

2023-12-14 04:09 UTC, hhtboy commented on main.py
> +                forum.append(name)
forum 배열을 직접 건들지 말고 함수 호출을 해주세요

2023-12-14 04:09 UTC, hhtboy commented on main.py
> +                forum.append(name)
forum 배열을 직접 건들지 말고 함수 호출을 통해 해주세요

2023-12-14 04:09 UTC, hhtboy commented on main.py
> +                forum.append(name)
여기도

2023-12-14 04:09 UTC, hhtboy commented on main.py
> +                forum.append(name)
여기랑

2023-12-14 04:09 UTC, hhtboy commented on main.py
> +                forum.append(name)
여기

2023-12-14 04:15 UTC, yyyy7246 commented on main.py
> +                forum.append(name)
함

2023-12-14 04:15 UTC, yyyy7246 commented on main.py
> +                forum.append(name)
함

2023-12-14 04:15 UTC, yyyy7246 commented on main.py
> +                forum.append(name)
함

2023-12-14 04:15 UTC, yyyy7246 commented on main.py
> +                forum.append(name)
함

2023-12-25 06:15 UTC, hhtboy approved these changes

2023-12-25 06:15 UTC, merged